# This workflow will run lint jobs
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: lint

on:
  # push:
  #   branches: ['main']
  pull_request:
    branches: ['main']
  workflow_run:
    workflows: [setup]
    branches-ignore: [main]
    types: [completed]

# on:
#   push:
#     branches: ['main']
#   pull_request:
#     branches: ['main']

jobs:
  # reference the setup workflow
  # setup:
  #   uses: ./.github/workflows/setup.yml
  eslint:
    # needs: [setup] # make the setup workflow a dependency
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }
    steps:
      - run: echo 'The triggering workflow passed'

    # strategy:
    #   matrix:
    #     node-version: [16.16.0]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # steps:
    #   - uses: actions/checkout@v3
    #   - name: Use Node.js ${{ matrix.node-version }}
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: ${{ matrix.node-version }}
    #       cache: 'npm'
    #   - run: npx eslint .
