# This workflow does a clean installation of node dependencies, and cache/restore them.
# It is meant to be called in other workflows as a first step.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_call

name: setup

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

# allow this workflow to be called from other workflows
# on: [workflow_call]

jobs:
  npm_ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.16.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
