# This workflow will do a clean installation of node dependencies, cache/restore them,
# lint jobs, tests, and typecheck
# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_call

name: workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  setup:
    name: clean install
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.16.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

  eslint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npx eslint .
