# This workflow will run lint jobs
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: WIP

on:
  # push:
  #   branches: ['main']
  pull_request:
    branches: ['main']
  workflow_run:
    workflows: [Setup]
    branches: [main]
    types: [completed]

jobs:
  no-condition:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'no condition needed'
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
