# This workflow will do a clean installation of node dependencies, cache/restore them,
# and run typescript type checking
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: svelte

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    paths-ignore:
      - '**.md'

jobs:
  svelte_check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.16.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npx svelte-check --tsconfig ./tsconfig.json --output human-verbose
